version: '3.8'
services:
  mssql:
    build: ./mssql/
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Secret1234
    ports:
      - '1433:1433'
    volumes:
      - db:/var/opt/mssql
      - ./backups/:/opt/mssql-tools/bin/
volumes:
  db:
    driver: local
