version: '3.8'
services:
  mssql:
    build: ./mssql/
    container_name: mssql
    restart: always
    env_file:
      - .env_prod
    ports:
      - '1433:1433'
    volumes:
      - db_data:/var/opt/mssql
      - ./backups/:/docker-entrypoint-initdb.d/
volumes:
  db_data:
